### PR TITLE
Add Juno to TMKMS

### PR DESCRIPTION
**Pull request by TaxiStake**

### CODE REVIEW

**Comment by TaxiStake** [comment]
Tested locally and it complies. 
```./tmkms init -n juno ~/testtmkms
    Creating /Users/user/testtmkms
   Generated KMS configuration: /Users/user/testtmkms/tmkms.toml
   Generated Secret Connection key: /Users/user/testtmkms/secrets/kms-identity.key```

**Comment by TaxiStake** [comment]
Confirmed working in production, main net Juno on our validator.

**Comment by tony-iqlusion** [comment]
@TaxiStake can you please rebase your branch? Thanks!

**Comment by tony-iqlusion** [comment]
Closing as stale

**Pull request closed without merging**
